name: stable
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- pip:
  - torch --index-url https://download.pytorch.org/whl/cu124
  - torchvision --index-url https://download.pytorch.org/whl/cu124
  - scipy
  - pillow
  - datasets
  - diffusers
  - accelerate
  - transformers
  - tqdm
  - timm
  - click
  - requests
  - psutil
