name: stable
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- pip:
  - torch --index-url https://download.pytorch.org/whl/cu124
  - torchvision --index-url https://download.pytorch.org/whl/cu124
  - diffusers==0.17.1
  - accelerate==0.23
  - transformers==4.34.1
  - datasets
  - pillow
